# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
#updat

jobs:
  create_and_deploy_front_end: #job name
    docker: # it uses the docker executor
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: deploy cloudfront
          #echo environment variable
          command: |
            aws cloudformation deploy --template-file bucket.yml --stack-name "chez-${CIRCLE_WORKFLOW_ID:0:7}" --parameter-overrides NAME="chez-${CIRCLE_WORKFLOW_ID:0:7}"
      - run: aws s3 sync . s3://"chez-${CIRCLE_WORKFLOW_ID:0:7}" --delete

  promote_to_production: #job name
    docker: # it uses the docker executor
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: promote to production
          #echo environment variable
          command: |
            aws cloudformation deploy \
            --template-file cloudfront.yml \
            --stack-name production-distro \
            --parameter-overrides PipelineID="chez-${CIRCLE_WORKFLOW_ID:0:7}"

  get_last_deployment_id: #job name
    docker: # it uses the docker executor
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: get last deployment id
          #echo environment variable
          command: |
            aws cloudformation \
            list-exports --query "Exports[?Name==\`PipelineID\`].Value" \
            --no-paginate --output text >> deployment_id.txt
  get_last_deployment_stack_name: #job name
    docker: # it uses the docker executor
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: get last deployment stack name
          #echo environment variable
          command: |
            aws cloudformation \
            list-exports --query "Exports[?Name==\`StackName\`].Value" \
            --no-paginate --output text >> stack_name.txt

  clean_up_old_front_end: #job name
    docker: # it uses the docker executor
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: export OldPipelineID=$(cat deployment_id.txt)
      - run: echo $OldPipelineID
      - run: export PreviousStackName=$(cat stack_name.txt)
      - run: echo $PreviousStackName
      - run: aws s3 rm s3://$OldPipelineID --recursive
      - run: aws cloudformation delete-stack --stack-name $PreviousStackName

  save_hello_world_output: #job name
    docker: # it uses the docker executor
      - image: amazon/aws-cli
    steps:
      - run: sudo apt-get install tar
      - run: echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: amazon/aws-cli
    steps:
      - run: sudo apt-get install tar
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt

workflows:
  # workflow
  my_workflow:
    jobs:
      # - create_and_deploy_front_end
      # - get_last_deployment_id:
      #     requires:
      #       - create_and_deploy_front_end
      # - get_last_deployment_stack_name:
      #     requires:
      #       - get_last_deployment_id
      # - promote_to_production:
      #     requires:
      #       - get_last_deployment_stack_name
      # - clean_up_old_front_end:
      #     requires:
      #       - promote_to_production
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
